<?php
$raq_post_type = array(
    array( 'id' => 'name',
        'type'=> 'text',
        'label' => 'Post type general name',
        'desc' => 'The handle (slug) name of the post type, usually plural.',
        'default' => 'reviews',
        // 'required' => 'true'
        ),
    array( 'id' => 'labels][menu_name', // or label
        'type' => 'text',
        'label' => 'Menu name',
        'desc' => 'display left menu label. same as name (if empty)',
        'default' => 'Reviews'
        ),
    array( 'id' => 'labels][singular_name',
        'type' => 'text',
        'label' => 'Singular name',
        'desc' => 'name for one object of this post type.',
        'placeholder' => 'e.g. article'
        ),
    array( 'id' => 'description',
        'type' => 'textarea',
        'label' => 'Description',
        'desc' => '',
        'cols' => '90',
        'placeholder' => 'Not have description'
        ),
    //labels|name_admin_bar
    array('id' => 'labels][add_new',
        'type' => 'text',
        'placeholder' => 'Добавить отзыв',
        'label' => 'Add new',
        'desc' => 'The add new text. The default is "Add New" for both hierarchical and non-hierarchical post types. When internationalizing this string, please use a gettext context matching your post type.'),
    array('id' => 'labels][add_new_item',
        'type' => 'text',
        'placeholder' => 'Добавить отзыв',
        'label' => 'Add new item',
        'desc' => 'Default is Add New Post/Add New Page'),
    array('id' => 'labels][new_item',
        'type' => 'text',
        'placeholder' => 'Новый отзыв',
        'label' => 'New item',
        'desc' => 'Default is New Post/New Page.'),
    array('id' => 'labels][edit_item',
        'type' => 'text',
        'placeholder' => 'Изменить отзыв',
        'label' => 'Edit item',
        'desc' => 'Default is Edit Post/Edit Page'),
    array('id' => 'labels][view_item',
        'type' => 'text',
        'placeholder' => 'Показать отзыв',
        'label' => 'View item',
        'desc' => 'Default is View Post/View Page.'),
    array('id' => 'labels][all_items',
        'type' => 'text',
        'placeholder' => 'Все отзывы',
        'label' => 'All items',
        'desc' => 'String for the submenu. Default is All Posts/All Pages.'),
    array('id' => 'labels][search_items',
        'type' => 'text',
        'placeholder' => 'Найти отзыв',
        'label' => 'Search items',
        'desc' => 'Default is Search Posts/Search Pages.'),
    array('id' => 'labels][not_found',
        'type' => 'text',
        'placeholder' => 'Отзывы не найдены',
        'label' => 'Not found',
        'desc' => 'Default is No posts found/No pages found.'),
    array('id' => 'labels][not_found_in_trash',
        'type' => 'text',
        'placeholder' => 'Отзывы в корзине не найдены',
        'label' => 'Not found in Trash',
        'desc' => 'Default is No posts found in Trash/No pages found in Trash.'),
    );